### ISSUE TITLE
Vampire block causes error

### ISSUE THREAD

**Issue by iotech-fvtt** [Brownie79/fvtt-swade-stat-block-parser#4]
This block from core SWADE:
```
Vampire
Blood-drinkers of lore are common in many
fantasy games. This is a relatively young
vampire minion. For weaker vampires, ignore
the Invulnerability Special Ability.
Attributes: Agility d8, Smarts d8, Spirit d8,
Strength d12+1, Vigor d10
Skills: Athletics d8, Common Knowledge d8,
Fighting d8, Intimidation d8, Notice d6,
Persuasion d8, Shooting d6, Stealth d10
Pace: 6; Parry: 6; Toughness: 9
Gear: -
Edges: Frenzy, Level Headed
Special Abilities:
@Bite/Claws: Str+d4.
@Invulnerability: Vampires can only be
slain by sunlight or a stake through the
heart (see those Weaknesses, below). They
may be Shaken by other attacks, but never
Wounded.
@Sire: Anyone slain by a vampire has a 50%
chance of rising as a vampire in 1d4 days.
@Undead: +2 Toughness; +2 to recover from
being Shaken; no additional damage from
Called Shots; ignores 1 point of Wound
penalties; doesn’t breathe; immune to
disease and poison.
@Weakness (Holy Symbol): A character with
a holy symbol may keep a vampire at bay
by displaying a holy symbol. A vampire
who wants to directly attack the victim
must beat her in an opposed Spirit roll.
@Weakness (Holy Water): A vampire
sprinkled with holy water is Fatigued. If
immersed, he combusts as if it were direct
sunlight (see below).
@Weakness (Invitation Only): Vampires cannot
enter a private dwelling without being
invited. They may enter public domains as
they please.
@Weakness (Stake Through the Heart):
A vampire hit with a Called Shot to the
heart (−4) must make a Vigor roll versus
the damage. If successful, it takes damage
normally. If it fails, it disintegrates to dust.
@Weakness (Sunlight): Vampires burn in
sunlight. They take 2d4 damage per round
until they are ash. Armor protects normally.
```
produces this error in console:
```
foundry.js:3023 Uncaught (in promise) Error: This is not a registered game setting
    at ClientSettings.get (foundry.js:3023)
    at searchCompendiumsForItem (importActorItems.js:200)
    at importActorGear (importActorItems.js:24)
    at importActorItems (importActorItems.js:4)
    at importActor (importActor.js:11)
    at buildActor (buildActor.js:23)
    at Object.callback (statblock-importer.js:43)
    at Dialog.submit (foundry.js:13496)
    at Dialog._onClickButton (foundry.js:13457)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
get @ foundry.js:3023
searchCompendiumsForItem @ importActorItems.js:200
importActorGear @ importActorItems.js:24
importActorItems @ importActorItems.js:4
importActor @ importActor.js:11
buildActor @ buildActor.js:23
callback @ statblock-importer.js:43
submit @ foundry.js:13496
_onClickButton @ foundry.js:13457
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
async function (async)
buildActor @ buildActor.js:23
callback @ statblock-importer.js:43
submit @ foundry.js:13496
_onClickButton @ foundry.js:13457
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

**Comment by iotech-fvtt** [comment]
Ancient Vampire produces the same error.

**Comment by iotech-fvtt** [comment]
Node.js console error:
```
FoundryVTT | 2020-06-24 20:12:13 | [error] The Compendium pack fvtt-swade-stat-block-parser.statblock-weapon already exists in the World and cannot be created
Error: The Compendium pack fvtt-swade-stat-block-parser.statblock-weapon already exists in the World and cannot be created
    at Function._onCreateCompendium (G:\Foundry47\resources\app\dist\database\documents\compendium.js:1:7804)
    at Function._onManageCompendium (G:\Foundry47\resources\app\dist\database\documents\compendium.js:1:7040)
    at Socket.handleEvent (G:\Foundry47\resources\app\dist\sockets.js:1:2028)
    at Socket.emit (events.js:311:20)
    at G:\Foundry47\resources\app\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by iotech-fvtt** [comment]
workaround: Had to delete ALL of the statblock import compendiums and refresh Foundry.

**Comment by spacemandev-git** [comment]
This is a problem with foundry version 0.6.4 (something is breaking in creating compendiums)
Currently only foundry version 0.6.2 is supported.
